### ISSUE TITLE
Application auto-creation not working as expected with more than one deploy/sts with auto-create labels

### ISSUE THREAD

**Issue by navidsh** [kappnav/issues#157]
### What did you do?

1. I created two deployments (named `app-1` and `app-2`) in the **same** namespace and added the following labels and annotations to both deployments:

```yaml
  labels:
    kappnav.app.auto-create: 'true'
  annotations:
    kappnav.app.auto-create.kinds: 'Deployment, StatefulSet, Service, Route, Ingress, ConfigMap'
    kappnav.app.auto-create.label: app.kubernetes.io/part-of
    kappnav.app.auto-create.labels-values: mega-app
    kappnav.app.auto-create.name: mega-app
```

2. kAppNav create an `Application` CR with the following annotations:
```yaml
  annotations:
    kappnav.app.auto-created.from.kind: Deployment
    kappnav.app.auto-created.from.name: app-1
```

3. I deleted `app-1` and the automatically generated `Application` CR got deleted.

### What did you expect to see?

I expected an `Application` CR to be available.

### What did you see instead?

The automatically generated `Application` CR got deleted and never got recreated.

### Environment

- kAppNav`v0.6.0`
- OpenShift `4.3`
