### ISSUE TITLE
Support for automatic application creation for Knative service

### ISSUE THREAD

**Issue by navidsh** [kappnav/issues#181]
Currently, kAppNav doesn't support automatic `Application` creation for Knative service based on the [kAppNav documentation](https://github.com/kappnav/design/blob/master/auto-app-lifecycle.md). It would be great if this scenario can be supported by adding `auto-create` labels to Knative Service resources.

**Comment by cvignola** [comment]
@navidsh The auto-create label is intended to be specified by the creator of the resource.  Is there a reason why KNative resources would not be handled the same way?

**Comment by navidsh** [comment]
@cvignola If the user adds the `kappnav.app.auto-create: true | false` label to a Knative Service, would kAppNav automatically create an Application CR for it?

**Comment by cvignola** [comment]
@navidsh auto-create is presently [supported for Deployment and Stateful](https://github.com/kappnav/design/blob/master/auto-app-lifecycle.md) set resource kinds only.  What resource kind would need to support auto-create for the Knative use case?

**Comment by navidsh** [comment]
@cvignola Users would create a Knative Service (`serving.knative.dev/Service`) for deploying their applications through Knative e.g.

```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: greeter
spec:
  template:
    spec:
      containers:
      - image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
```

IMO, the Knative Service is the right place for adding auto-create labels.

Users can now pick Knative Service from within the Developer dashboard on OCP, it would be nice story to be able to auto-create Application CR by adding a proper kAppNav labels there.
![image](https://user-images.githubusercontent.com/2364853/80742177-f541d700-8ae8-11ea-9bb2-15d2394a6f12.png)
