### ISSUE TITLE
Case conversion during auto-create causes empty app

### ISSUE THREAD

**Issue by rlcundiff** [kappnav/issues#213]
Deployment has label: 
```
app.kubernetes.io/part-of: Triggers
```

Because of the required conversion of the name to domain name format, App Nav auto-creates app with:
```
  name: triggers
...
  selector:
    matchLabels:
      app.kubernetes.io/part-of: triggers
```
