### ISSUE TITLE
For command actions, show job status, not application-style status

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#33]
Current status for a command actions shows application style status of  normal/warning/problem, using this mapping: 

- Normal is displayed when job:

  1. is pending (hasn't run yet) 
  1. is running
  1. has finished successfully (status.conditions[0].type=COMPLETE)

- Warning is not used.

- Problem is displayed if the Job ends in failed state (status.conditions[0].type=FAILED).   

The trouble is a user cannot look at a job and know if it ended.  It would be far more helpful to have job-specific status values like these: 

1. pending
1. running
1. succeeded
1. failed 

The purpose of this issue is change the job status from normal/warning/problem to pending/running/succeeded/failed.   

The new mapping rule will be based on following pod-related fields: 

- status.active number of pods running 
- status.succeeded number of pods succeeded 
- status.failed number of pods failed 

Note the status subfields of active/succeeded/failed only exist when the job has one or more pods in that state.  Note also command action jobs only ever have one pod and restarts are not allowed.  This makes the fields active/succeeded/failed mutually exclusive in the case of command action jobs. 

1. pending - none of these fields exist:   active/succeeded/failed
1. running - active field exists 
1. succeeded - succeeded field exists 
1. failed - failed field exists 

For the purpose of bubbling worst severity to the top, the precedence order should be (highest precedence first): 

1. failed
1. pending
1. running
1. succeeded

Must also have a mapping from text status (preceding list) to colors.  Proposed: 

1. failed - red
1. pending - yellow
1. running - grey 
1. succeeded - green 

Could use some help from design to finish the color mapping.

**Comment by cvignola** [comment]
MVP for first iteration: 

2. No clear indication after completion whether or not the action was successful.
3. No easy access to the log.

**Comment by pgnyeste** [comment]
![01 Click Action on component](https://user-images.githubusercontent.com/51239735/67884294-f420f480-fb1b-11e9-8cfd-c0e48342e3d1.png)
![02 See Action dialog](https://user-images.githubusercontent.com/51239735/67884331-06029780-fb1c-11e9-825f-20f75bcb5127.png)
![03 Action status](https://user-images.githubusercontent.com/51239735/68137203-96622300-fef4-11e9-9725-dd6d4b18906b.png)

The Action Status Toast will be on the top right.  Thus, no matter what screen you are on, it will show and you can get status of the action and get to the log.

**Comment by cvignola** [comment]
The Toaster is good and should display whatever status completion status value(s) we decide.  The purpose of this issue is to revisit the status values.

**Comment by k8vance88** [comment]
This issue was discussed on the 3ib today.  We will split command actions work into separate work items, where this work item only covers updating the status color/words.  Another issue will cover giving the command actions view a facelift.

The status values should be the following:
In Progress - blue
Failed - red
Completed - green
Pending - yellow

However, currently the UI only handles 2 cases - 
 1. In Progess/Completed is green (Normal)
 2. Failed is red (Problem)

The current way we get the status for complete/failed is correct.  But we also need to detect an In Progress state and a Pending state.  My observation is that an In Progress job status looks like this:
status:
  startTime: '2020-02-17T20:36:40Z'
  active: 1

I have not successfully been able to create a Pending job status, but I think it would be where there are no conditions and active is <1.  More investigation needs to be done to prove that theory. 

This work requires a new command action status map for colors/states. We need to use the same status processing for the toaster notifications.

**Comment by kinueng** [comment]
Examples from running command `oc get jobs -n kinueng -o yaml` in my OCP 4.3 test environment

## Example of `Pending` job
Oddly, I accidentally was able to get a Pod to be in `Pending` state, but OCP reports the Job associated with the Pending pod as "In Progress"

### Job full YAML
```
kind: Job
apiVersion: batch/v1
metadata:
  name: kappnav-20ef9427-cb68-4ca0-8d9e-61f82be34703
  namespace: kappnav
  selfLink: >-
    /apis/batch/v1/namespaces/kappnav/jobs/kappnav-20ef9427-cb68-4ca0-8d9e-61f82be34703
  uid: e6329cc4-fe45-4da2-90e4-d1af17bcaa2f
  resourceVersion: '18136440'
  creationTimestamp: '2020-02-21T19:51:19Z'
  labels:
    kappnav-job-component-sub-kind: liberty
    kappnav-job-type: command
    kappnav-job-component-name: loyalty-level
    kappnav-job-user-id: kubeadmin
    kappnav-job-application-namespace: default
    kappnav-job-action-name: sleepfailed
    kappnav-job-component-kind: Deployment
    kappnav-job-application-name: stock-trader
    kappnav-job-component-namespace: default
  annotations:
    kappnav-job-action-text: Sleep Failed
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 4
  selector:
    matchLabels:
      controller-uid: e6329cc4-fe45-4da2-90e4-d1af17bcaa2f
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: e6329cc4-fe45-4da2-90e4-d1af17bcaa2f
        job-name: kappnav-20ef9427-cb68-4ca0-8d9e-61f82be34703
    spec:
      containers:
        - name: kappnav-1bca2049-ce51-4df5-a625-aafeebacf2dd
          image: 'docker.io/kinueng/app-nav-cmds:latest'
          command:
            - exit
            - '1'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: kappnav-sa
      serviceAccount: kappnav-sa
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      schedulerName: default-scheduler
status:
  startTime: '2020-02-21T19:51:19Z'
  active: 1
```
### Partial Pod's YAML from OCP console for the Job
```
status:
  phase: Pending
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-02-21T19:50:56Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-02-21T19:50:56Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status:
        [kappnav-1bca2049-ce51-4df5-a625-aafeebacf2dd]
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2020-02-21T19:50:56Z'
      reason: ContainersNotReady
      message: >-
        containers with unready status:
        [kappnav-1bca2049-ce51-4df5-a625-aafeebacf2dd]
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2020-02-21T19:51:19Z'
  hostIP: 10.16.34.115
  podIP: 10.254.5.61
  podIPs:
    - ip: 10.254.5.61
  startTime: '2020-02-21T19:50:56Z'
  containerStatuses:
    - name: kappnav-1bca2049-ce51-4df5-a625-aafeebacf2dd
      state:
        waiting:
          reason: CreateContainerError
          message: >
            container create failed: time="2020-02-24T20:55:47Z" level=error
            msg="container_linux.go:346: starting container process caused
            \"exec: \\\"exit\\\": executable file not found in $PATH\""

            container_linux.go:346: starting container process caused "exec:
            \"exit\": executable file not found in $PATH"
      lastState: {}
      ready: false
      restartCount: 0
      image: 'docker.io/kinueng/app-nav-cmds:latest'
      imageID: ''
      started: false
  qosClass: BestEffort
```

## Example of a `In Progress` job
```
...
  status:
    active: 1
    startTime: "2020-02-18T21:52:29Z"
```


## Example of a `Completed` job
```
...
  status:
    completionTime: "2020-02-18T21:19:36Z"
    conditions:
    - lastProbeTime: "2020-02-18T21:19:36Z"
      lastTransitionTime: "2020-02-18T21:19:36Z"
      status: "True"
      type: Complete
    startTime: "2020-02-18T21:18:22Z"
    succeeded: 1
```
